lang: node_js
node_js:
  - "6"

before_install:
  - npm install
  
before_script:
  - npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  repo: framevuerk/public
  target_branch: master
  fqdn: framevuerk.com
  script:
    - npm run build
  on:
    branch: master