lang: node_js

node_js:
  - "6"

before_install:
  - npm install
  
test:
  before_script:
    - npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  target_branch: master
  fqdn: framevuerk.com
  repo: framevuerk/public
  script:
    - npm run build
  on:
    branch: master