lang: node_js

sudo: false

node_js:
  - "node"
  - "6"

before_install:
  - npm install

before_script:
  - npm run test
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  target_branch: master
  fqdn: framevuerk.com
  repo: framevuerk/public
  on:
    branch: master